config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks do
    member do
      post 'complete', to: 'tasks#complete'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description, presence: true
  validates :status, presence: true

  scope :uncompleted, -> { where(status: 'uncompleted') }
  scope :completed, -> { where(status: 'completed') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @uncompleted_tasks = Task.uncompleted
    @completed_tasks = Task.completed
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    @task.status = 'uncompleted'
    if @task.save
      redirect_to root_path, notice: 'Task created'
    else
      redirect_to root_path,
                  alert: "Task is invalid. #{@task.errors.full_messages.first}"
    end
  end

  def complete
    @task = Task.find(params[:id])
    @task.status = 'completed'
    if @task.save
      redirect_to root_path, notice: 'Task completed'
    end
  end

  private

  def task_params
    params.require(:task).permit(:description, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="main-wrapper">
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: "alert alert-#{name}" %>
    <% end -%>

    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.text_field :description, placeholder: 'Description', class: 'description-field' %>
  <%= f.submit 'Add task', :disable_with => 'Adding task...', class: 'right btn btn-success' %>
<% end -%>

app/views/tasks/index.html.erb
<div class="row">
  <div class="column">
    <h3>Task list</h3>
    <table class="uncompleted-tasks">
      <tbody>
        <% if @uncompleted_tasks.any? %>
          <% @uncompleted_tasks.each do |task| %>
            <tr>
              <td class="task-item">
                <span class="left">
                  <%= task.description %>
                </span>
                <span class="right">
                  <%= button_to 'Complete', complete_task_path(task), method: :post, :class => 'btn btn-primary complete' %>
                </span>
              </td>
            </tr>
          <% end %>
        <% end %>

        <tr><td><%= render 'form' %></td></tr>
      </tbody>
    </table>
  </div>

  <div class="column">
    <% if @completed_tasks.any? %>
    <table class="completed-tasks">
      <caption>Completed tasks</caption>
      <tbody>
        <% @completed_tasks.each do |task| %>
          <tr>
            <td class="task-item mark-as-complete">
              <%= task.description %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
<div>